### ISSUE TITLE
Atmega88PB and Atmega328PB

### ISSUE THREAD

**Issue by mamejay** [SukkoPera/OpenPSX2AmigaPadAdapter#16]
Hey there.  I have a bunch of Atmega88PB and Atmega328PB chips available which I would like to finally use for something.
There is a bootloader for the 328PB in the github but nothing for the 88PB.  Can I just use the bootloader from Ardunio IDE?
Last thing the firmware 88p and 328p.  Can I use these files with the PB chips or do I have to recompile the binaries again?  Probably a silly question but I am not great with these things.

Thanks!

**Comment by zambujal** [comment]
Sukkopera said that the 88 had lack of memory so it's impossible to fit the bootloader, you have to use an programmer for this tyoe of chips, allthough an 88p worked with lag with me...  I wonder If it was an faulty chip. 328p worked nicely.

**Comment by SukkoPera** [comment]
Sorry, somehow I missed this issue.

I heven't touched this thing in a while, but I think the code does no longer fit on an ATmega88... Or maybe it does by a very small margin, which basically rules out the bootloader.

The 'PB variant work mostly fine, but these models do not properly support a quartz-based clock. In my experience this means that sometimes the board will not start or it will crash if you just touch the board. You can use the Arduino bootloader anyway, in case, and since I never distributed pre-compiled binaries, you will have to compile the code yourself. Use MiniCore with these CPUs.

@zambujal's issue with the '88 was just the fuses not being set, I seem to recall we solved this elsewhere.

Hope it helps.
